### ISSUE TITLE
Cannot co-exist with existing Mysql server

### ISSUE THREAD

**Issue by provegard** [stumpdk/MySql.Server#1]
I'm using MySql.Server to test my DB functionality, and it works really well. Today I installed a real Mysql server on my machine to be able to test my application in a live setting, but suddenly all my tests stopped working.

The first issue is that MySql.Server tries to kill all mysqld processes. This fails for the real server since it (luckily) runs under a different account.

The real problem, though, is that the mysqld process that MySql.Server starts stops right away. I suppose it has to do with conflicting arguments:

http://dev.mysql.com/doc/refman/5.7/en/multiple-servers.html

Maybe it's possible to reconfigure my main server (I'll try that), but it feels as if MySql.Server should adapt to the environment rather than vice versa. Do you agree?

**Comment by provegard** [comment]
Actually, the first issue is pretty severe. MySql.Server kills the real MySql server process on the build server during a build.

**Comment by stumpdk** [comment]
I've made a new version which only kills the relevant process (!). But I'm not able to test it at the moment,
Concerning the arguments: Do you mean the possibility to chose a custom port for the test server? The rest of the arguments should be irrelevant for the test server.

**Comment by stumpdk** [comment]
I've released a new package that should fix this problem. Let me know if it isn't the case.

**Comment by provegard** [comment]
Thanks, I'll try it!

**Comment by provegard** [comment]
This seemed to work. I just ran a build on the CI server and the Mysql instance running there survived!
