### ISSUE TITLE
StartServer() function throws exception if there is already MySqlServer Instance running

### ISSUE THREAD

**Issue by NazmiAltun** [stumpdk/MySql.Server#11]
I have MySql installed on my computer, and when i try to run my  test , it throws error as below ;

**> Server could not be started.Authentication to host '127.0.0.1' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'localhost' (using password: NO)**

This my test code;

```
public override void CleanUp()
        {
            if (dbServer != null)
            {
                dbServer.ShutDown();
            }
        }
        public override Func<DbConnectionConfiguration> Initialize()
        {
            dbServer = MySqlServer.Instance;
            CleanUp();
            dbServer.StartServer();//Throws exception
            MySqlHelper.ExecuteNonQuery(dbServer.GetConnectionString(), "CREATE DATABASE TestDataBase;");

            return () =>
            {
                return new DbConnectionConfiguration()
                {
                    DataProvider = MySqlProviderInvariantName.ProviderName,
                    ConnectionString = dbServer.GetConnectionString("TestDataBase"),
                };
            };
        }

```
This test runs well on PCs that mySql have  not installed on it. It fails on PC that MySql server installed and running.

My question is , how can i make this test running even when there is MySql Server installed on the PC?

Thanks,

**Comment by stumpdk** [comment]
Hi, 
When you are using a test running on a system with an existing MySQL server, you have to use another port than the default (3306).
You can start the server using another port like this: MySqlServer.StartServer(int serverPort): 

Let me know if it helps you.

**Comment by NazmiAltun** [comment]
Hello, 
I've tried it as ; 

`dbServer.StartServer(3316);`

and with some another different ports , but still throws exception. It works when i manually stop  MySql service from Service Management.

Edit :  I am using   MySQL Server 5.7

**Comment by NazmiAltun** [comment]
Sorry,  my comment is misleading.  When  I've changed the port, it doesn't throw exception on **StartServer** function anymore. I throws error at following line ;

`   MySqlHelper.ExecuteNonQuery(dbServer.GetConnectionString(), "CREATE DATABASE TestDataBase;");`


And this is the exception message : 

> {"Authentication to host '127.0.0.1' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'localhost' (using password: NO)"}

**Comment by NazmiAltun** [comment]
Ok , i've found a solution  ;
Problem is connection string that returns from function ; 

`dbServer.GetConnectionString()`

This function returns connection string as ; 

> **Server=127.0.0.1;Port=3316;Protocol=pipe;**

I assume when you add **"Protocol=pipe"** to connection string, it tries to connect to MySql Instance that is already installed rather than the one we create for testing.

When I set connection string manually as ; 
```
...
dbServer = MySqlServer.Instance;
dbServer.StartServer(3316);
MySqlHelper.ExecuteNonQuery("Server=127.0.0.1;Port=3316;", "CREATE DATABASE TestDataBase;");
.....
```

It worked
