### ISSUE TITLE
Make it possible to specify a custom port for the test instance

### ISSUE THREAD

**Issue by provegard** [stumpdk/MySql.Server#2]
See #1 

To prevent the test server from conflicting with any real server instance on the current machine, I would like to configure the test server to run on a custom port. 

Something like passing a config object to `StartServer` would be perfect.

**Comment by stumpdk** [comment]
I've given the code an overhaul.
One of the changes is, that it is now possible to run the server on a specific port, like this:
dbServer.StartServer(3300);

Are you able to build and test it yourself?

**Comment by stumpdk** [comment]
@provegard: I've given the code an overhaul.
One of the changes is that it's now possible to run the server on a specific port, like this:
dbServer.StartServer(3300);

I've made a release candidate based on [this branch](https://github.com/stumpdk/MySql.Server/tree/divide_server_and_connector).
Get it [here](https://github.com/stumpdk/MySql.Server/releases/tag/1.0.0-beta).

Let me hear if it works for you.

**Comment by provegard** [comment]
Thanks, I'll have a look!

**Comment by provegard** [comment]
Sorry for the delay - it works well!
