### ISSUE TITLE
TestKillProcess test fails After Shutdown() 

### ISSUE THREAD

**Issue by sweetbub** [stumpdk/MySql.Server#6]
Expose ProcessId property.  After Closing process search by Id and not by name.  If more than one instance was running search by name gives appearance that process wasn't killed.

**Comment by sweetbub** [comment]
i see in the beta version another way to verify that a process was killed.  it works, although there is no guarantee that it's accurate.  I was going to close this case, but after some thought I think exposing ProcessId is a better way to go.

**Comment by stumpdk** [comment]
The problem with old processes is better handled in [release 1.0](https://github.com/stumpdk/MySql.Server/releases/tag/1.0.0).
I've extended the API with the possibility to get the process id (MySqlServer.ProcessId).
